# Generated by Django 5.2.6 on 2025-09-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_customerprofile_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
