# Generated by Django 5.2.6 on 2025-10-20 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customerprofile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='is_verified',
        ),
    ]
