# Generated by Django 5.2.6 on 2025-10-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_customerprofile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='email_token',
        ),
    ]
