# Generated by Django 5.2.6 on 2025-09-20 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(max_length=255)),
                ('shipping_email', models.CharField(max_length=255)),
                ('shipping_Address1', models.CharField(max_length=400)),
                ('shipping_Address2', models.CharField(blank=True, max_length=400, null=True)),
                ('shipping_city', models.CharField(max_length=70)),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_country', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
    ]
