# Generated by Django 5.2.6 on 2025-09-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0004_rename_sipping_address1_shippingaddress_shipping_address1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_pay',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
