# Generated by Django 5.2.6 on 2025-09-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_rename_shipping_address1_shippingaddress_sipping_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='sipping_Address1',
            new_name='shipping_Address1',
        ),
    ]
