# Generated by Django 5.2.6 on 2025-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_alter_order_amount_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_pay',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
